#include "Plans/TestPlans/TestKick/constraints/TestKickMaster1472647610805Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1472647610805) ENABLED START*/
//Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
//Plan:TestKickMaster

/*		
 * Tasks: 
 * - EP:1472647610808 : DefaultTask (1225112227903)
 *
 * States:
 * - Idle (1472647610806)
 * - Running (1472648628993)
 *
 * Vars:
 */

// State: Idle

// State: Idle

// State: Running

// State: Running

}
