#include "Plans/TestPlans/TestKick/constraints/TestKickRunning1472647818767Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1472647818767) ENABLED START*/
//Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
//Plan:TestKickRunning

/*		
 * Tasks: 
 * - EP:1472647848896 : DefaultTask (1225112227903)
 *
 * States:
 * - DriveToA (1472647848895)
 * - DriveToB (1472648701821)
 * - GetBall (1472648712038)
 * - Kick (1472648717255)
 * - Idle (1472648733912)
 *
 * Vars:
 */

// State: DriveToA

// State: DriveToA

// State: DriveToB

// State: DriveToB

// State: GetBall

// State: GetBall

// State: Kick

// State: Kick

// State: Idle

// State: Idle

}
