#include "Plans/DummyPlan1482486227468.h"
using namespace alica;
/*PROTECTED REGION ID(eph1482486227468) ENABLED START*/ //Add additional using directives here
/*PROTECTED REGION END*/
namespace alicaAutogenerated
{
    //Plan:DummyPlan

    /* generated comment
     
     Task: DefaultTask  -> EntryPoint-ID: 1482486227473

     */
    shared_ptr<UtilityFunction> UtilityFunction1482486227468::getUtilityFunction(Plan* plan)
    {
        /*PROTECTED REGION ID(1482486227468) ENABLED START*/

        shared_ptr < UtilityFunction > defaultFunction = make_shared < DefaultUtilityFunction > (plan);
        return defaultFunction;

        /*PROTECTED REGION END*/
    }

//State: NewState in Plan: DummyPlan

}
