#ifndef TestKickRunningCONSTRAINT_H_
#define TestKickRunning_H_
#include "engine/BasicConstraint.h"
#include <memory>

using namespace std;
using namespace alica;

namespace alica
{
    class ConstraintDescriptor;
    class RunningPlan;
}

namespace alicaAutogenerated
{

} /* namespace alica */

#endif /* TestKickRunningCONSTRAINT_H_ */
