#include "Plans/TestPlans/TestKick/TestKickMaster1472647610805.h"
using namespace alica;
/*PROTECTED REGION ID(eph1472647610805) ENABLED START*/ //Add additional using directives here
#include <MSLWorldModel.h>
#include <Game.h>
/*PROTECTED REGION END*/
namespace alicaAutogenerated
{
    //Plan:TestKickMaster

    /* generated comment
     
     Task: DefaultTask  -> EntryPoint-ID: 1472647610808

     */
    shared_ptr<UtilityFunction> UtilityFunction1472647610805::getUtilityFunction(Plan* plan)
    {
        /*PROTECTED REGION ID(1472647610805) ENABLED START*/

        shared_ptr < UtilityFunction > defaultFunction = make_shared < DefaultUtilityFunction > (plan);
        return defaultFunction;

        /*PROTECTED REGION END*/
    }

    //State: Idle in Plan: TestKickMaster

    /*
     *		
     * Transition:
     *   - Name: MISSING_NAME, ConditionString: , Comment : Idle2Run 
     *
     * Plans in State: 
     *
     * Tasks: 
     *   - DefaultTask (1225112227903) (Entrypoint: 1472647610808)
     *
     * States:
     *   - Idle (1472647610806)
     *   - Running (1472648628993)
     *
     * Vars:
     */
    bool TransitionCondition1472648640273::evaluate(shared_ptr<RunningPlan> rp)
    {
        /*PROTECTED REGION ID(1472648638637) ENABLED START*/
        return wm->game->checkSituation(msl::Situation::Start);
        /*PROTECTED REGION END*/

    }

    //State: Running in Plan: TestKickMaster

    /*
     *		
     * Transition:
     *   - Name: MISSING_NAME, ConditionString: , Comment : Run2Idle 
     *
     * Plans in State: 				
     *   - Plan - (Name): TestKickRunning, (PlanID): 1472647818767 
     *
     * Tasks: 
     *   - DefaultTask (1225112227903) (Entrypoint: 1472647610808)
     *
     * States:
     *   - Idle (1472647610806)
     *   - Running (1472648628993)
     *
     * Vars:
     */
    bool TransitionCondition1472648641417::evaluate(shared_ptr<RunningPlan> rp)
    {
        /*PROTECTED REGION ID(1472648640369) ENABLED START*/
    	return wm->game->checkSituation(msl::Situation::Stop);
        /*PROTECTED REGION END*/

    }

}
