#include "Plans/TestPlans/TestKick/TestKickRunning1472647818767.h"
using namespace alica;
/*PROTECTED REGION ID(eph1472647818767) ENABLED START*/ //Add additional using directives here
/*PROTECTED REGION END*/
namespace alicaAutogenerated
{
    //Plan:TestKickRunning

    /* generated comment
     
     Task: DefaultTask  -> EntryPoint-ID: 1472647848896

     */
    shared_ptr<UtilityFunction> UtilityFunction1472647818767::getUtilityFunction(Plan* plan)
    {
        /*PROTECTED REGION ID(1472647818767) ENABLED START*/

        shared_ptr < UtilityFunction > defaultFunction = make_shared < DefaultUtilityFunction > (plan);
        return defaultFunction;

        /*PROTECTED REGION END*/
    }

    //State: DriveToA in Plan: TestKickRunning

    /*
     *		
     * Transition:
     *   - Name: MISSING_NAME, ConditionString: , Comment : DriveToA2DriveToB 
     *
     * Plans in State: 				
     *   - Plan - (Name): TestDriveToA, (PlanID): 1472648841944 				
     *   - Plan - (Name): DribbleControlDefault, (PlanID): 1449742099555 
     *
     * Tasks: 
     *   - DefaultTask (1225112227903) (Entrypoint: 1472647848896)
     *
     * States:
     *   - DriveToA (1472647848895)
     *   - DriveToB (1472648701821)
     *   - GetBall (1472648712038)
     *   - Kick (1472648717255)
     *   - Idle (1472648733912)
     *
     * Vars:
     */
    bool TransitionCondition1472648742636::evaluate(shared_ptr<RunningPlan> rp)
    {
        /*PROTECTED REGION ID(1472648741815) ENABLED START*/
        return rp->anyChildrenStatus(PlanStatus::Success);
        /*PROTECTED REGION END*/

    }

    //State: DriveToB in Plan: TestKickRunning

    /*
     *		
     * Transition:
     *   - Name: MISSING_NAME, ConditionString: , Comment : DriveToB2Kick 
     *
     * Plans in State: 				
     *   - Plan - (Name): TestDriveToB, (PlanID): 1472648852426 				
     *   - Plan - (Name): DribbleControlDefault, (PlanID): 1449742099555 
     *
     * Tasks: 
     *   - DefaultTask (1225112227903) (Entrypoint: 1472647848896)
     *
     * States:
     *   - DriveToA (1472647848895)
     *   - DriveToB (1472648701821)
     *   - GetBall (1472648712038)
     *   - Kick (1472648717255)
     *   - Idle (1472648733912)
     *
     * Vars:
     */
    bool TransitionCondition1472648743524::evaluate(shared_ptr<RunningPlan> rp)
    {
        /*PROTECTED REGION ID(1472648742732) ENABLED START*/
        return rp->anyChildrenStatus(PlanStatus::Success);
        /*PROTECTED REGION END*/

    }

    //State: GetBall in Plan: TestKickRunning

    /*
     *		
     * Transition:
     *   - Name: MISSING_NAME, ConditionString: , Comment : GetBall2DriveToA 
     *
     * Plans in State: 				
     *   - Plan - (Name): TestGetBallDefault, (PlanID): 1472647982006 
     *
     * Tasks: 
     *   - DefaultTask (1225112227903) (Entrypoint: 1472647848896)
     *
     * States:
     *   - DriveToA (1472647848895)
     *   - DriveToB (1472648701821)
     *   - GetBall (1472648712038)
     *   - Kick (1472648717255)
     *   - Idle (1472648733912)
     *
     * Vars:
     */
    bool TransitionCondition1472648741726::evaluate(shared_ptr<RunningPlan> rp)
    {
        /*PROTECTED REGION ID(1472648740577) ENABLED START*/
        return rp->anyChildrenStatus(PlanStatus::Success);
        /*PROTECTED REGION END*/

    }

    //State: Kick in Plan: TestKickRunning

    /*
     *		
     * Transition:
     *   - Name: MISSING_NAME, ConditionString: , Comment : Kick2Idle 
     *
     * Plans in State: 				
     *   - Plan - (Name): TestKickDefault, (PlanID): 1472648373489 
     *
     * Tasks: 
     *   - DefaultTask (1225112227903) (Entrypoint: 1472647848896)
     *
     * States:
     *   - DriveToA (1472647848895)
     *   - DriveToB (1472648701821)
     *   - GetBall (1472648712038)
     *   - Kick (1472648717255)
     *   - Idle (1472648733912)
     *
     * Vars:
     */
    bool TransitionCondition1472648744508::evaluate(shared_ptr<RunningPlan> rp)
    {
        /*PROTECTED REGION ID(1472648743629) ENABLED START*/
        return rp->anyChildrenStatus(PlanStatus::Success);
        /*PROTECTED REGION END*/

    }

//State: Idle in Plan: TestKickRunning

}
