#include "Plans/constraints/DummyPlan1482486227468Constraints.h"
using namespace std;
using namespace alica;
/*PROTECTED REGION ID(ch1482486227468) ENABLED START*/
//Add additional using directives here
/*PROTECTED REGION END*/

namespace alicaAutogenerated
{
//Plan:DummyPlan

/*		
 * Tasks: 
 * - EP:1482486227473 : DefaultTask (1225112227903)
 *
 * States:
 * - NewState (1482486227470)
 *
 * Vars:
 */

// State: NewState

// State: NewState

}
